services:
  weapons-reporter:
    build: .
    ports:
      - "5009:5009"
    hostname: weapons-reporter
    container_name: weapons-reporter
    working_dir: /app
    command: ["python3", "app.py"]
    environment:
      - FLASK_HOST=${FLASK_HOST}
      - FLASK_PORT=${FLASK_PORT}
      - DEBUG=${DEBUG}
      - KAFKA_SERVER=${KAFKA_SERVER}
      - RESPONSE_TOPIC=${RESPONSE_TOPIC}
      - GROUP_ID=${GROUP_ID}

networks:
  default:
    driver: bridge
